apiVersion: apps/v1
kind: Deployment
metadata:
  name: ub-deployment
spec:
  selector:
    matchLabels:
      app: ub-app
  replicas: 1
  template:
    metadata:
      labels:
        app: ub-app
    spec:
      containers:
      - name: ub-novnc
        image: zhujq/ub-novnc
        ports:
            - containerPort: 6901
              protocol: TCP
        env:
           - name: VNC_RESOLUTION
             value: 1920x1080
        resources:
            limits:
              cpu: 2000m
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 256Mi
